import {PrismaClient} from "../lib/generated/prisma-node/client";import {Role} from "../lib/enums";import bcrypt from "bcryptjs";
const db=new PrismaClient();
async function main(){
 const adminHash=await bcrypt.hash(process.env.ADMIN_PASSWORD||"VeloraAdmin2026!",12);
 const ownerHash=await bcrypt.hash("OwnerDemo2026!",12);const customerHash=await bcrypt.hash("CustomerDemo2026!",12);
 const admin=await db.user.upsert({where:{email:process.env.ADMIN_EMAIL||"admin@velora.energy"},update:{passwordHash:adminHash,role:Role.ADMIN},create:{name:"Platform Administrator",email:process.env.ADMIN_EMAIL||"admin@velora.energy",passwordHash:adminHash,role:Role.ADMIN}});
 const owner=await db.user.upsert({where:{email:"owner@velora.demo"},update:{passwordHash:ownerHash,role:Role.BUSINESS_OWNER},create:{name:"Demo Business Owner",email:"owner@velora.demo",passwordHash:ownerHash,role:Role.BUSINESS_OWNER}});
 await db.user.upsert({where:{email:"customer@velora.demo"},update:{passwordHash:customerHash,role:Role.CUSTOMER},create:{name:"Demo Customer",email:"customer@velora.demo",passwordHash:customerHash,role:Role.CUSTOMER}});
 for(const item of [{fuelType:"Regular 95",fuelTypeAr:"عادي ٩٥",price:1.89},{fuelType:"Performance 98",fuelTypeAr:"ممتاز ٩٨",price:2.12},{fuelType:"Eco Diesel",fuelTypeAr:"ديزل صديق للبيئة",price:1.76}])await db.gasPrice.upsert({where:{fuelType:item.fuelType},update:{price:item.price,fuelTypeAr:item.fuelTypeAr},create:item});
 const existing=await db.business.findFirst({where:{ownerId:owner.id,name:"Velora Global Mobility"}});
 if(!existing)await db.business.create({data:{name:"Velora Global Mobility",nameAr:"فيلورا العالمية للتنقل",type:"GAS_STATION",description:"A globally inspired mobility hub combining energy, vehicle care and premium convenience.",descriptionAr:"مركز تنقل بروح عالمية يجمع الطاقة والعناية بالمركبات وسبل الراحة المميزة.",phone:"+1 800 835 672",email:"owner@velora.demo",status:"APPROVED",currency:"USD",ownerId:owner.id,services:{create:[{name:"Signature Car Wash",nameAr:"غسيل السيارات المميز",description:"Premium exterior and interior care.",descriptionAr:"عناية مميزة بالمظهر الخارجي والداخلي.",price:39,duration:45},{name:"Precision Oil Service",nameAr:"خدمة الزيت الدقيقة",description:"Certified oil and filter replacement.",descriptionAr:"تغيير معتمد للزيت والفلتر.",price:89,duration:60}]},stations:{create:[{name:"Velora Manhattan",nameAr:"فيلورا مانهاتن",address:"350 Fifth Avenue",addressAr:"٣٥٠ الجادة الخامسة",city:"New York",cityAr:"نيويورك",country:"United States",countryAr:"الولايات المتحدة",timezone:"America/New_York",latitude:40.7484,longitude:-73.9857,phone:"+1 212 555 0101",amenities:JSON.stringify(["E-Mart","Coffee","Car Care"])},{name:"Velora Marina",nameAr:"فيلورا مارينا",address:"Marina Boulevard",addressAr:"جادة مارينا",city:"Singapore",cityAr:"سنغافورة",country:"Singapore",countryAr:"سنغافورة",timezone:"Asia/Singapore",latitude:1.2834,longitude:103.8607,phone:"+65 6555 0102",amenities:JSON.stringify(["E-Mart","EV Charging","Car Care"])},{name:"Velora Central",nameAr:"فيلورا سنترال",address:"Potsdamer Platz",addressAr:"ساحة بوتسدام",city:"Berlin",cityAr:"برلين",country:"Germany",countryAr:"ألمانيا",timezone:"Europe/Berlin",latitude:52.5096,longitude:13.376,phone:"+49 30 555 0103",amenities:JSON.stringify(["E-Mart","Coffee","EV Charging"])}]}}});
 const products=[{name:"Midnight Detail Kit",nameAr:"طقم العناية الليلي",description:"Premium interior and exterior care essentials.",descriptionAr:"أساسيات عناية مميزة للداخل والخارج.",category:"Car Care",categoryAr:"العناية بالسيارة",price:38,stock:12,imageUrl:"/products/detail.png",featured:true},{name:"Velora Reserve Coffee",nameAr:"قهوة فيلورا ريزيرف",description:"Single-origin cold brew, bottled fresh.",descriptionAr:"قهوة باردة أحادية المصدر، معبأة طازجة.",category:"Refreshments",categoryAr:"مرطّبات",price:4.9,stock:32,imageUrl:"/products/coffee.png",featured:true},{name:"Mineral Water No. 8",nameAr:"مياه معدنية رقم ٨",description:"Still spring water in recyclable glass.",descriptionAr:"مياه ينابيع غير غازية في زجاج قابل لإعادة التدوير.",category:"Refreshments",categoryAr:"مرطّبات",price:2.8,stock:64,imageUrl:"/products/water.png",featured:false}];
 for(const p of products){const found=await db.product.findFirst({where:{name:p.name}});if(found)await db.product.update({where:{id:found.id},data:p});else await db.product.create({data:p})}
 await db.auditLog.create({data:{actorId:admin.id,action:"SEED_COMPLETED",entityType:"System",entityId:"global-demo",metadata:JSON.stringify({version:2})}});
 console.log("Global demo data ready");
}
main().finally(()=>db.$disconnect());
