import {notFound} from "next/navigation";import {prisma} from "@/lib/prisma";import {LocationActions} from "@/components/LocationActions";import {Clock3,MapPin,Phone,Star} from "lucide-react";import {money} from "@/lib/format";export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:{id:string}}){const item=await prisma.station.findUnique({where:{id:params.id},select:{name:true,city:true,country:true}});return item?{title:item.name,description:`Services and directions for ${item.name} in ${item.city}, ${item.country}.`}:{title:"Location"}}
export default async function Location({params}:{params:{id:string}}){
 const station=await prisma.station.findFirst({where:{id:params.id,OR:[{businessId:null},{business:{status:"APPROVED"}}]},include:{business:{include:{services:{where:{active:true}}}}}});
 if(!station)notFound();
 const reviews=station.businessId?await prisma.review.findMany({where:{businessId:station.businessId},include:{user:{select:{name:true}}},orderBy:{createdAt:"desc"}}):[],rating=reviews.length?reviews.reduce((sum,item)=>sum+item.rating,0)/reviews.length:null;
 const lat=Number(station.latitude),lng=Number(station.longitude),mapUrl=`https://www.openstreetmap.org/export/embed.html?bbox=${lng-.02}%2C${lat-.02}%2C${lng+.02}%2C${lat+.02}&layer=mapnik&marker=${lat}%2C${lng}`;
 return <section className="mx-auto min-h-screen max-w-7xl px-5 py-16"><div className="grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow">{station.business?.type.replaceAll("_"," ")||"Mobility location"}</p><h1 className="display mt-4 text-6xl md:text-8xl">{station.name}</h1><div className="mt-7 flex flex-wrap gap-4 text-sm text-white/50"><span><MapPin className="mr-2 inline h-4 w-4 text-gold"/>{station.address}, {station.city}, {station.country}</span><span><Clock3 className="mr-2 inline h-4 w-4 text-gold"/>{station.openingTime}–{station.closingTime}</span><span><Phone className="mr-2 inline h-4 w-4 text-gold"/>{station.phone}</span>{rating&&<span><Star className="mr-2 inline h-4 w-4 text-gold"/>{rating.toFixed(1)}</span>}</div><div className="glass mt-10 overflow-hidden rounded-[2rem]"><iframe title="OpenStreetMap" className="h-[450px] w-full border-0" src={mapUrl}/></div></div><aside><h2 className="font-serif text-3xl">Services</h2><div className="mt-5 space-y-3">{station.business?.services.map(service=><div key={service.id} className="glass flex justify-between rounded-2xl p-5"><div><b>{service.name}</b><p className="mt-1 text-xs text-white/35">{service.duration} minutes</p></div><b className="text-gold">{money(service.price,station.business?.currency)}</b></div>)}</div><div className="mt-8"><LocationActions stationId={station.id} businessId={station.businessId||undefined}/></div><h2 className="mt-10 font-serif text-3xl">Recent reviews</h2><div className="mt-4 space-y-3">{reviews.slice(0,5).map(review=><div key={review.id} className="rounded-2xl bg-white/5 p-4"><b>{review.user.name} · {review.rating}/5</b><p className="mt-2 text-sm text-white/40">{review.comment}</p></div>)}</div></aside></div></section>
}
